namespace NodeJS {
  interface ProcessEnv {
    DATABASE_STRING: string;

    ACCESS_TOKEN_TTL: number;
    REFRESH_TOKEN_TTL: number;

    INFURA_BSC_PROVIDER: string;
    INFURA_BSC_TESTNET_PROVIDER: string;
    INFURA_ETHEREUM_PROVIDER: string;
    INFURA_ETHEREUM_TESTNET_PROVIDER: string;
    INFURA_POLYGON_PROVIDER: string;
    INFURA_POLYGON_TESTNET_PROVIDER: string;
    NEXT_PUBLIC_MNEMONIC: string;

    ACCESS_TOKEN_PRIVATE_KEY: string;
    REFRESH_TOKEN_PRIVATE_KEY: string;

    SALT_WORK_FACTOR: number;

    NODE_RSA_PRIVATE_KEY: string;

    NEXT_PUBLIC_INFURA_API_KEY_SECRET: string;
    NEXT_PUBLIC_INFURA_IPFS_PROJECT_ID: string;
  }
}
